version: '2'

services:

  influxdb:
    image: influxdb:latest
    ports:
      - '8087:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=stagioptr
      - INFLUXDB_ADMIN_USER=stagioptr
      - INFLUXDB_ADMIN_PASSWORD=stagioptr@2019
    restart: always
    networks:
      - data_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3006:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=stagioptr
      - GF_SECURITY_ADMIN_PASSWORD=stagioptr
    networks:
      - data_net

networks:
  data_net:
    driver: bridge

volumes:
  influxdb-storage:
  grafana-storage: